name: TestDriver.ai

permissions:
  actions: read
  contents: read
  statuses: write
  pull-requests: write

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  gather-test-files:
    name: Gather Test Files
    runs-on: ubuntu-latest
    outputs:
      test_files: ${{ steps.test_list.outputs.files }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.ref }}

      - name: Find all test files and extract filenames
        id: test_list
        run: |
          FILES=$(ls ./testdriver/*.yaml)
          FILENAMES=$(basename -a $FILES)
          FILES_JSON=$(echo "$FILENAMES" | jq -R -s -c 'split("\n")[:-1]')
          echo "::set-output name=files::$FILES_JSON"
  test:
    needs: gather-test-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows] # the runner OS
        test: ${{ fromJson(needs.gather-test-files.outputs.test_files) }}
      fail-fast: false
    name: ${{ matrix.os }} - ${{ matrix.test }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: testdriverai/action@main
        with:
          os: ${{ contains(matrix.os, 'windows') && 'windows' || 'linux' }}
          version: "5.7.5"
          prerun: |
            cd $env:TEMP
            npm init -y
            npm install dashcam-chrome
            Start-Process "C:/Program Files/Google/Chrome/Application/chrome.exe" -ArgumentList "--start-maximized", "--no-default-browser-check", "--no-first-run", "--disable-features=PasswordManagerEnabled", "--load-extension=$(pwd)/node_modules/dashcam-chrome/build", ${{ env.TD_WEBSITE }}
            exit
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: |
            1. /run testdriver/${{ matrix.test }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
          TD_WEBSITE: "google.com"
          TD_EXTENSION_NAME: "ColorZilla"
